name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build Hex Fiend
      run: xcodebuild -scheme Release -derivedDataPath build 
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: "Hex Fiend.app"
        path: "build/Build/Products/Release/Hex Fiend.app"
